### ISSUE TITLE
[Feature] Parse and Serialize JSON and XML

### ISSUE THREAD

**Issue by KamyaPA** [ECDAR-AAU-SW-P5/Ecdar-GUI-Web#15]
### Description
Read the previos .xml and .json files.
Create them as TypeScript classes

Types
- [x]  Location
- [x]  Edge
- [x]  System
- [x]  Component
- [x]  Query

Pre pull
- [x] Documentation
- [x] Testing

**Comment by atjn** [comment]
Whoops sorry
