### ISSUE TITLE
[BUG] Canvas does not get cleared when creating a new project

### ISSUE THREAD

**Issue by DenFlyvendeGed** [ECDAR-AAU-SW-P5/Ecdar-GUI-Web#161]
### Description

When having a component in view, and creating a new project, the canvas will still contain the component of the previous project. Clicking on the component will result in console errors as the component should not exist in the project.

### Steps To Reproduce

steps to reproduce the behavior:
1. open an example
2. click on a component
3. click New Project under the file tab

**Comment by atjn** [comment]
Good find!
